name: Deploy Gatsby Static Assets to S3 Bucket
env:
  owner: SharjeelSafdar
  repo: project14d-pet-theory-event-driven

# Controls when the action will run. Triggers the workflow on
# 1) push event for main branch
# 2) pull_request generated on main branch
# 3) It's triggered only by changes in relavent files in client/ directory.
on:
  push:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "backend/**"
      - "client/.gitignore"
      - "client/README.md"
      - "client/.prettierignore"
      - "client/.prettierrc"
      - "client/LICENSE"
      - ".github/workflows/deployBackendServicesStack.yml"
      - ".github/workflows/deployFrontendBucketAndDist.yml"
  pull_request:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "backend/**"
      - "client/.gitignore"
      - "client/README.md"
      - "client/.prettierignore"
      - "client/.prettierrc"
      - "client/LICENSE"
      - ".github/workflows/deployBackendServicesStack.yml"
      - ".github/workflows/deployFrontendBucketAndDist.yml"

jobs:
  Deploy_Gatsby_Static_Assets_to_S3_Bucket:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client

      - name: Build Gatsby App
        working-directory: client
        run: npm run build

      - name: Deploy Static Site to S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_PROJECT_REGION  }}
          SOURCE_DIR: client/public
